### ISSUE TITLE
Evaluation of the baseline model(s)

### ISSUE THREAD

**Issue by dars180602** [dars180602/Credit-Card-Fraud-Detection#7]
• Perform a comprehensive evaluation of the trained baseline model(s) using  appropriate evaluation metrics.
• Assess model performance using metrics such as accuracy, precision, recall, F1-score, and AUC-ROC.
• Analyze the strengths and weaknesses of the baseline model(s) to identify areas for improvement.

**Comment by dars180602** [comment]
![Models](https://github.com/dars180602/Credit-Card-Fraud-Detection/assets/139527052/0a5a5297-6255-45f4-943c-69a9f667965e)
@mumuljuve Please check it and approved. Thank you

**Comment by mumuljuve** [comment]
After check those results and trying some changes in the models to try to increase the accuracy and recall, I realized we are not getting significant changes, and those metrics among our models are correct. I approved it.

**Comment by mumuljuve** [comment]
After check those results and trying some changes in the models to try to increase the accuracy and recall, I realized we are not getting significant changes, and those metrics among our models are correct. I approved it.
