### ISSUE TITLE
Hyperparemeter tuning and modifications

### ISSUE THREAD

**Issue by dars180602** [dars180602/Credit-Card-Fraud-Detection#8]
• Conduct hyperparameter tuning to optimize the performance of the baseline model(s).
• Explore different hyperparameter configurations and optimization techniques such as grid  search, random search, and Bayesian optimization.
• Implement modifications to the model architecture or algorithm parameters based on  insights gained from the evaluation phase.

**Comment by mumuljuve** [comment]
We performed two algorithms of hyperparameter tunning:  Grid Search applied to Balanced Random Forest Classifier and Randomized Search Cross-Validation applied to Balanced Random Forest Classifier after SMOTE. In both cases our accuracy and recall were similar to the results obtained before hyperparameter tunning, even worse. Our hyperparameters used were n_estimators, max_depth, min_samples_split, min_samples_leaf and sampling_strategy. 

For that reason, after running those techniques, we tried a different approach ridding off some features after evaluating the correlation with the correlation matrix as reference. Same or very similar results were gotten. So at that point we can say we have reached one of the highest accuracy and recall we can get with the dataset without using heavy algorithms of hyperparameter tunning due processing power.
