### ISSUE TITLE
Model validation with test dataset

### ISSUE THREAD

**Issue by dars180602** [dars180602/Credit-Card-Fraud-Detection#9]
• Validate the tuned model(s) using a separate test dataset to assess generalization performance.
• Ensure that the validated model(s) maintain consistent performance across unseen data.
• Compare the performance of the validated model(s) with the baseline to measure the effectiveness of the tuning and modifications.

**Comment by mumuljuve** [comment]
![image](https://github.com/dars180602/Credit-Card-Fraud-Detection/assets/73260947/69494140-8acd-4628-aee3-5bfaa544b8f4)
Here we can see the metrics of our models after some modifications trying to increase accuracy as deleting some columns, but we got similar results or even worse, also we ran the hyperparameter tunning models, with no better results, here showing 60% precision and 89% of recall being similar to the results gotten with the Balanced Random Forest Classifier After SMOTE model. 

Those results were given using the test data, which was the 20% of the data from our initial dataset.
